export const ideaToSpecWorkspace = {
  api_version: "v1",
  artifact_kind: "specspace_idea_to_spec_workspace",
  schema_version: 1,
  generated_at: "2026-06-21T00:00:00+00:00",
  read_only: true,
  canonical_mutations_allowed: false,
  tracked_artifacts_written: false,
  source: { provider: "fixture", read_only: true },
  summary: {
    status: "blocked",
    available_artifact_count: 6,
    missing_artifact_count: 0,
    candidate_node_count: 2,
    candidate_edge_count: 1,
    pre_sib_finding_count: 1,
    repair_action_count: 2,
    repair_context_required_count: 1,
    materialized_file_count: 2,
    promotion_path_count: 0,
    promotion_gate_blocker_count: 1,
    next_artifact: "owner/operator repair before promotion",
  },
  intake: {
    available: true,
    active_frame: {
      project: "DemoCalculator",
      ontology_refs: ["ontology://specgraph-core"],
      domain_refs: ["domain.calculator"],
      context_refs: ["context.idea_to_spec"],
    },
    summary: {
      actor_count: 1,
      domain_event_count: 1,
      command_count: 1,
      policy_count: 1,
      external_system_count: 0,
      constraint_count: 1,
      vocabulary_question_count: 1,
      context_completion_question_count: 0,
    },
  },
  candidate_graph: {
    available: true,
    active_frame: {
      project: "DemoCalculator",
      ontology_refs: ["ontology://specgraph-core"],
      domain_refs: ["domain.calculator"],
      context_refs: ["context.idea_to_spec"],
    },
    summary: {
      node_count: 2,
      edge_count: 1,
      requirement_count: 2,
      acceptance_criteria_count: 1,
      claim_count: 1,
      gap_count: 1,
    },
    pre_sib_readiness: { ready: true, review_state: "ready_for_pre_sib" },
    nodes: [
      {
        id: "candidate-spec.calculator-product",
        title: "Calculator Product",
        kind: "product_boundary",
        ontology_refs: ["ontology://specgraph-core#Spec"],
        requirement_count: 1,
        acceptance_criteria_count: 1,
        claim_count: 1,
        gap_count: 0,
      },
      {
        id: "candidate-spec.numeric-input",
        title: "Numeric Input",
        kind: "feature",
        ontology_refs: [],
        requirement_count: 1,
        acceptance_criteria_count: 0,
        claim_count: 0,
        gap_count: 1,
      },
    ],
  },
  pre_sib: {
    available: true,
    readiness: {
      ready: false,
      review_state: "pre_sib_review_required",
      blocked_by: ["pre_sib_ontology_coverage_gap"],
    },
    metrics: {
      node_count: 2,
      edge_count: 1,
      orphan_node_count: 0,
      ontology_coverage_ratio: 0.5,
    },
    findings: [
      {
        finding_id: "pre_sib_ontology_coverage_gap",
        severity: "review_required",
        message: "Every candidate node should carry ontology refs.",
        source_ref: "runs/pre_sib_coherence_report.json",
      },
    ],
  },
  repair_loop: {
    available: true,
    readiness: {
      ready: true,
      review_state: "repair_preview_ready",
      next_artifact: "runs/idea_to_spec_workspace_bundle.json",
    },
    summary: {
      status: "repair_preview_ready",
      action_count: 2,
      applied_action_count: 1,
      context_required_count: 1,
    },
    metric_delta_projection: {
      delta: {
        edge_count: 1,
        acceptance_criteria_count: 1,
      },
    },
    actions: [
      {
        id: "repair.add-ac.req-input-digits",
        kind: "add_acceptance_criterion",
        status: "applied_to_preview",
        target_ref: "req.input.digits",
        rationale: "Add a reviewable placeholder acceptance criterion.",
        source_findings: ["pre_sib_acceptance_criteria_gap"],
      },
      {
        id: "repair.ontology-gap.candidate-spec-numeric-input",
        kind: "add_ontology_gap",
        status: "requires_context",
        target_ref: "candidate-spec.numeric-input",
        rationale: "Ontology refs need owner context.",
        source_findings: ["pre_sib_ontology_coverage_gap"],
      },
    ],
  },
  materialization: {
    available: true,
    readiness: {
      ready: true,
      review_state: "materialized_candidate_review_ready",
      next_artifact: "Platform graph-repository promotion-request",
    },
    summary: {
      status: "materialized_candidate_review_ready",
      materialized_file_count: 2,
      candidate_node_count: 2,
      finding_count: 0,
    },
    materialization_source: "repair_loop_preview",
    files: [
      {
        candidate_node_id: "candidate-spec.calculator-product",
        materialized_id: "CANDIDATE-CANDIDATE-SPEC-CALCULATOR-PRODUCT",
        path: "runs/materialized_candidate_specs/CANDIDATE-CANDIDATE-SPEC-CALCULATOR-PRODUCT.yaml",
        promotion_path: "runs/materialized_candidate_specs/CANDIDATE-CANDIDATE-SPEC-CALCULATOR-PRODUCT.yaml",
      },
      {
        candidate_node_id: "candidate-spec.numeric-input",
        materialized_id: "CANDIDATE-CANDIDATE-SPEC-NUMERIC-INPUT",
        path: "runs/materialized_candidate_specs/CANDIDATE-CANDIDATE-SPEC-NUMERIC-INPUT.yaml",
        promotion_path: "runs/materialized_candidate_specs/CANDIDATE-CANDIDATE-SPEC-NUMERIC-INPUT.yaml",
      },
    ],
    promotion_request: {
      path_argument: "--path",
      platform_artifact_kind: "platform_graph_repository_promotion_request",
      paths: [
        "runs/materialized_candidate_specs/CANDIDATE-CANDIDATE-SPEC-CALCULATOR-PRODUCT.yaml",
        "runs/materialized_candidate_specs/CANDIDATE-CANDIDATE-SPEC-NUMERIC-INPUT.yaml",
      ],
    },
  },
  promotion_gate: {
    available: true,
    readiness: {
      ready: false,
      review_state: "idea_to_spec_promotion_blocked",
      blocked_by: ["repair_context_required"],
      next_artifact: "owner/operator repair before promotion",
    },
    summary: {
      status: "idea_to_spec_promotion_blocked",
      finding_count: 1,
      warning_count: 0,
      promotion_path_count: 0,
      materialized_file_count: 2,
    },
    metric_snapshot: {
      pre_sib: {
        ontology_coverage_ratio: 0.5,
      },
      materialized_file_count: 2,
      promotion_path_count: 0,
    },
    findings: [
      {
        finding_id: "repair_context_required",
        severity: "review_required",
        message: "Owner/operator context is still required.",
        source_ref: "idea_to_spec_promotion_gate",
      },
    ],
    promotion_request: {
      path_argument: "--path",
      platform_artifact_kind: "platform_graph_repository_promotion_request",
      paths: [],
    },
  },
  artifacts: {
    event_storming_intake: {
      available: true,
      path: "runs/idea_event_storming_intake.json",
      artifact_kind: "idea_event_storming_intake",
      status: "ready_for_candidate_graph",
      proposal_id: "0149",
      contract_ref: "specgraph.idea-to-spec.event-storming-intake.v0.1",
    },
    candidate_graph: {
      available: true,
      path: "runs/candidate_spec_graph.json",
      artifact_kind: "candidate_spec_graph",
      status: "ready_for_pre_sib",
      proposal_id: "0150",
      contract_ref: "specgraph.idea-to-spec.candidate-spec-graph.v0.1",
    },
    pre_sib: {
      available: true,
      path: "runs/pre_sib_coherence_report.json",
      artifact_kind: "pre_sib_coherence_report",
      status: "pre_sib_review_required",
      proposal_id: "0151",
      contract_ref: "specgraph.idea-to-spec.pre-sib-coherence-report.v0.1",
    },
    repair_loop: {
      available: true,
      path: "runs/candidate_repair_loop_report.json",
      artifact_kind: "candidate_repair_loop_report",
      status: "repair_preview_ready",
      proposal_id: "0152",
      contract_ref: "specgraph.idea-to-spec.candidate-repair-loop.v0.1",
    },
    materialization: {
      available: true,
      path: "runs/candidate_spec_materialization_report.json",
      artifact_kind: "candidate_spec_materialization_report",
      status: "materialized_candidate_review_ready",
      proposal_id: "0153",
      contract_ref: "specgraph.idea-to-spec.candidate-spec-materialization.v0.1",
    },
    promotion_gate: {
      available: true,
      path: "runs/idea_to_spec_promotion_gate.json",
      artifact_kind: "idea_to_spec_promotion_gate",
      status: "idea_to_spec_promotion_blocked",
      proposal_id: "0154",
      contract_ref: "specgraph.idea-to-spec.promotion-gate.v0.1",
    },
  },
  display_limits: {
    nodes: 40,
    findings: 40,
    repair_actions: 40,
    materialized_files: 40,
  },
  authority_boundary: {
    idea_to_spec_workspace_is_authority: false,
    may_execute_prompt_agent: false,
    may_mutate_candidate_source_artifacts: false,
    may_mutate_canonical_specs: false,
    may_write_ontology_package: false,
    may_create_branch_or_commit: false,
    may_mark_candidate_accepted: false,
  },
};
