export const ideaToSpecWorkspace = {
  api_version: "v1",
  artifact_kind: "specspace_idea_to_spec_workspace",
  schema_version: 1,
  generated_at: "2026-06-21T00:00:00+00:00",
  read_only: true,
  canonical_mutations_allowed: false,
  tracked_artifacts_written: false,
  source: { provider: "fixture", read_only: true },
  selected_workspace_id: "team-decision-log",
  workspace: {
    available: true,
    id: "team-decision-log",
    display_name: "Team Decision Log",
    public_route: "/team-decision-log",
    workflow_lane: "product_idea_to_spec",
    target_repository_role: "product_spec_workspace",
    governance_profile: "product_workspace",
    authority_profile: "workspace_owner_controlled",
    source_mode: "active_candidate",
    ready: true,
    review_state: "active_candidate_ready",
    blocked_by: [],
    next_artifact: "SpecSpace product workspace route",
  },
  summary: {
    status: "blocked",
    available_artifact_count: 6,
    missing_artifact_count: 0,
    candidate_node_count: 2,
    candidate_edge_count: 1,
    pre_sib_finding_count: 1,
    repair_action_count: 2,
    repair_context_required_count: 1,
    materialized_file_count: 2,
    promotion_path_count: 0,
    promotion_gate_blocker_count: 1,
    platform_missing_artifact_count: 0,
    git_service_operation_count: 3,
    git_service_error_count: 0,
    next_artifact: "owner/operator repair before promotion",
  },
  intake: {
    available: true,
    active_frame: {
      project: "DemoCalculator",
      ontology_refs: ["ontology://specgraph-core"],
      domain_refs: ["domain.calculator"],
      context_refs: ["context.idea_to_spec"],
    },
    summary: {
      actor_count: 1,
      domain_event_count: 1,
      command_count: 1,
      policy_count: 1,
      external_system_count: 0,
      constraint_count: 1,
      vocabulary_question_count: 1,
      context_completion_question_count: 0,
    },
  },
  candidate_graph: {
    available: true,
    active_frame: {
      project: "DemoCalculator",
      ontology_refs: ["ontology://specgraph-core"],
      domain_refs: ["domain.calculator"],
      context_refs: ["context.idea_to_spec"],
    },
    summary: {
      node_count: 2,
      edge_count: 1,
      requirement_count: 2,
      acceptance_criteria_count: 1,
      claim_count: 1,
      gap_count: 1,
    },
    pre_sib_readiness: { ready: true, review_state: "ready_for_pre_sib" },
    nodes: [
      {
        id: "candidate-spec.calculator-product",
        title: "Calculator Product",
        kind: "product_boundary",
        ontology_refs: ["ontology://specgraph-core#Spec"],
        requirement_count: 1,
        acceptance_criteria_count: 1,
        claim_count: 1,
        gap_count: 0,
      },
      {
        id: "candidate-spec.numeric-input",
        title: "Numeric Input",
        kind: "feature",
        ontology_refs: [],
        requirement_count: 1,
        acceptance_criteria_count: 0,
        claim_count: 0,
        gap_count: 1,
      },
    ],
  },
  pre_sib: {
    available: true,
    readiness: {
      ready: false,
      review_state: "pre_sib_review_required",
      blocked_by: ["pre_sib_ontology_coverage_gap"],
    },
    metrics: {
      node_count: 2,
      edge_count: 1,
      orphan_node_count: 0,
      ontology_coverage_ratio: 0.5,
    },
    findings: [
      {
        finding_id: "pre_sib_ontology_coverage_gap",
        severity: "review_required",
        message: "Every candidate node should carry ontology refs.",
        source_ref: "runs/pre_sib_coherence_report.json",
      },
    ],
  },
  repair_loop: {
    available: true,
    readiness: {
      ready: true,
      review_state: "repair_preview_ready",
      next_artifact: "runs/idea_to_spec_workspace_bundle.json",
    },
    summary: {
      status: "repair_preview_ready",
      action_count: 2,
      applied_action_count: 1,
      context_required_count: 1,
    },
    metric_delta_projection: {
      delta: {
        edge_count: 1,
        acceptance_criteria_count: 1,
      },
    },
    actions: [
      {
        id: "repair.add-ac.req-input-digits",
        kind: "add_acceptance_criterion",
        status: "applied_to_preview",
        target_ref: "req.input.digits",
        rationale: "Add a reviewable placeholder acceptance criterion.",
        source_findings: ["pre_sib_acceptance_criteria_gap"],
      },
      {
        id: "repair.ontology-gap.candidate-spec-numeric-input",
        kind: "add_ontology_gap",
        status: "requires_context",
        target_ref: "candidate-spec.numeric-input",
        rationale: "Ontology refs need owner context.",
        source_findings: ["pre_sib_ontology_coverage_gap"],
      },
    ],
  },
  materialization: {
    available: true,
    readiness: {
      ready: true,
      review_state: "materialized_candidate_review_ready",
      next_artifact: "Platform graph-repository promotion-request",
    },
    summary: {
      status: "materialized_candidate_review_ready",
      materialized_file_count: 2,
      candidate_node_count: 2,
      finding_count: 0,
    },
    materialization_source: "repair_loop_preview",
    files: [
      {
        candidate_node_id: "candidate-spec.calculator-product",
        materialized_id: "CANDIDATE-CANDIDATE-SPEC-CALCULATOR-PRODUCT",
        path: "runs/materialized_candidate_specs/CANDIDATE-CANDIDATE-SPEC-CALCULATOR-PRODUCT.yaml",
        promotion_path: "runs/materialized_candidate_specs/CANDIDATE-CANDIDATE-SPEC-CALCULATOR-PRODUCT.yaml",
      },
      {
        candidate_node_id: "candidate-spec.numeric-input",
        materialized_id: "CANDIDATE-CANDIDATE-SPEC-NUMERIC-INPUT",
        path: "runs/materialized_candidate_specs/CANDIDATE-CANDIDATE-SPEC-NUMERIC-INPUT.yaml",
        promotion_path: "runs/materialized_candidate_specs/CANDIDATE-CANDIDATE-SPEC-NUMERIC-INPUT.yaml",
      },
    ],
    promotion_request: {
      path_argument: "--path",
      platform_artifact_kind: "platform_graph_repository_promotion_request",
      paths: [
        "runs/materialized_candidate_specs/CANDIDATE-CANDIDATE-SPEC-CALCULATOR-PRODUCT.yaml",
        "runs/materialized_candidate_specs/CANDIDATE-CANDIDATE-SPEC-NUMERIC-INPUT.yaml",
      ],
    },
  },
  promotion_gate: {
    available: true,
    readiness: {
      ready: false,
      review_state: "idea_to_spec_promotion_blocked",
      blocked_by: ["repair_context_required"],
      next_artifact: "owner/operator repair before promotion",
    },
    summary: {
      status: "idea_to_spec_promotion_blocked",
      finding_count: 1,
      warning_count: 0,
      promotion_path_count: 0,
      materialized_file_count: 2,
    },
    metric_snapshot: {
      pre_sib: {
        ontology_coverage_ratio: 0.5,
      },
      materialized_file_count: 2,
      promotion_path_count: 0,
    },
    findings: [
      {
        finding_id: "repair_context_required",
        severity: "review_required",
        message: "Owner/operator context is still required.",
        source_ref: "idea_to_spec_promotion_gate",
      },
    ],
    promotion_request: {
      path_argument: "--path",
      platform_artifact_kind: "platform_graph_repository_promotion_request",
      paths: [],
    },
  },
  controlled_promotion: {
    available: true,
    platform_request: {
      available: true,
      ok: true,
      candidate_id: "idea-alpha",
      candidate_branch: "graph-candidate/idea-alpha",
      commit_paths: [
        "runs/materialized_candidate_specs/CANDIDATE-CANDIDATE-SPEC-CALCULATOR-PRODUCT.yaml",
        "runs/materialized_candidate_specs/CANDIDATE-CANDIDATE-SPEC-NUMERIC-INPUT.yaml",
      ],
      requested_operations: [
        "prepare_branch",
        "create_commit",
        "open_review",
      ],
      review: {
        title: "Add candidate spec graph",
        base_branch: "main",
      },
      summary: {
        error_count: 0,
        commit_path_count: 2,
        promotion_ready: true,
      },
    },
    git_service_execution: {
      available: true,
      ok: true,
      dry_run: false,
      open_review_dry_run: true,
      candidate_id: "idea-alpha",
      candidate_ref: "graph-candidate/idea-alpha",
      workspace_dir: ".platform/candidates/idea-alpha-worktree",
      operation_count: 3,
      completed_operation_count: 3,
      error_count: 0,
      copied_file_count: 1,
      operations: [
        {
          name: "prepare_worktree",
          status: "succeeded",
          request_artifact_kind: "platform_git_service_prepare_worktree_request",
          response_artifact_kind: "platform_git_service_prepare_worktree_response",
          report_ref:
            ".platform/candidates/idea-alpha-worktree/.platform/graph_repository_worktree_prepare_report.json",
          diagnostic_count: 0,
        },
        {
          name: "commit_candidate",
          status: "succeeded",
          request_artifact_kind: "platform_git_service_commit_candidate_request",
          response_artifact_kind: "platform_git_service_commit_candidate_response",
          report_ref:
            ".platform/candidates/idea-alpha-worktree/.platform/graph_repository_review_commit_report.json",
          diagnostic_count: 0,
        },
        {
          name: "open_review",
          status: "dry_run",
          request_artifact_kind: "platform_git_service_open_review_request",
          response_artifact_kind: "platform_git_service_open_review_response",
          report_ref: null,
          diagnostic_count: 0,
        },
      ],
      report_refs: {
        prepare_worktree:
          ".platform/candidates/idea-alpha-worktree/.platform/graph_repository_worktree_prepare_report.json",
        commit_candidate:
          ".platform/candidates/idea-alpha-worktree/.platform/graph_repository_review_commit_report.json",
      },
    },
    action_boundary: {
      inspect_only: true,
      acknowledge_only: true,
      may_execute_git_service: false,
      may_create_branch_or_commit: false,
      may_merge_review: false,
      may_mutate_specs: false,
    },
  },
  artifacts: {
    event_storming_intake: {
      available: true,
      path: "runs/idea_event_storming_intake.json",
      artifact_kind: "idea_event_storming_intake",
      status: "ready_for_candidate_graph",
      proposal_id: "0149",
      contract_ref: "specgraph.idea-to-spec.event-storming-intake.v0.1",
    },
    candidate_graph: {
      available: true,
      path: "runs/candidate_spec_graph.json",
      artifact_kind: "candidate_spec_graph",
      status: "ready_for_pre_sib",
      proposal_id: "0150",
      contract_ref: "specgraph.idea-to-spec.candidate-spec-graph.v0.1",
    },
    pre_sib: {
      available: true,
      path: "runs/pre_sib_coherence_report.json",
      artifact_kind: "pre_sib_coherence_report",
      status: "pre_sib_review_required",
      proposal_id: "0151",
      contract_ref: "specgraph.idea-to-spec.pre-sib-coherence-report.v0.1",
    },
    repair_loop: {
      available: true,
      path: "runs/candidate_repair_loop_report.json",
      artifact_kind: "candidate_repair_loop_report",
      status: "repair_preview_ready",
      proposal_id: "0152",
      contract_ref: "specgraph.idea-to-spec.candidate-repair-loop.v0.1",
    },
    materialization: {
      available: true,
      path: "runs/candidate_spec_materialization_report.json",
      artifact_kind: "candidate_spec_materialization_report",
      status: "materialized_candidate_review_ready",
      proposal_id: "0153",
      contract_ref: "specgraph.idea-to-spec.candidate-spec-materialization.v0.1",
    },
    promotion_gate: {
      available: true,
      path: "runs/idea_to_spec_promotion_gate.json",
      artifact_kind: "idea_to_spec_promotion_gate",
      status: "idea_to_spec_promotion_blocked",
      proposal_id: "0154",
      contract_ref: "specgraph.idea-to-spec.promotion-gate.v0.1",
    },
    platform_promotion_request: {
      available: true,
      path: "runs/graph_repository_promotion_request.json",
      artifact_kind: "platform_graph_repository_promotion_request",
      status: null,
      proposal_id: null,
      contract_ref: null,
    },
    git_service_execution: {
      available: true,
      path: "runs/git_service_promotion_execution_report.json",
      artifact_kind: "platform_git_service_promotion_execution_report",
      status: null,
      proposal_id: null,
      contract_ref: null,
    },
  },
  display_limits: {
    nodes: 40,
    findings: 40,
    repair_actions: 40,
    materialized_files: 40,
    git_service_operations: 20,
  },
  authority_boundary: {
    idea_to_spec_workspace_is_authority: false,
    may_execute_prompt_agent: false,
    may_mutate_candidate_source_artifacts: false,
    may_mutate_canonical_specs: false,
    may_write_ontology_package: false,
    may_create_branch_or_commit: false,
    may_execute_git_service_operation: false,
    may_mark_candidate_accepted: false,
  },
};
