export const ideaToSpecWorkspace = {
  api_version: "v1",
  artifact_kind: "specspace_idea_to_spec_workspace",
  schema_version: 1,
  generated_at: "2026-06-21T00:00:00+00:00",
  read_only: true,
  canonical_mutations_allowed: false,
  tracked_artifacts_written: false,
  source: { provider: "fixture", read_only: true },
  selected_workspace_id: "team-decision-log",
  workspace: {
    available: true,
    id: "team-decision-log",
    display_name: "Team Decision Log",
    public_route: "/team-decision-log",
    workflow_lane: "product_idea_to_spec",
    target_repository_role: "product_spec_workspace",
    governance_profile: "product_workspace",
    authority_profile: "workspace_owner_controlled",
    source_mode: "active_candidate",
    ready: true,
    review_state: "active_candidate_ready",
    blocked_by: [],
    next_artifact: "SpecSpace product workspace route",
  },
  summary: {
    status: "blocked",
    available_artifact_count: 16,
    missing_artifact_count: 0,
    candidate_node_count: 2,
    candidate_edge_count: 1,
    ontology_seed_gap_count: 2,
    ontology_seed_binding_count: 5,
    pre_sib_finding_count: 1,
    repair_action_count: 2,
    clarification_request_count: 1,
    ontology_decision_count: 1,
    resolved_ontology_gap_count: 1,
    unresolved_ontology_gap_count: 7,
    rerun_removed_gap_count: 1,
    repair_context_required_count: 1,
    materialized_file_count: 2,
    promotion_path_count: 0,
    promotion_gate_blocker_count: 1,
    platform_missing_artifact_count: 0,
    git_service_operation_count: 3,
    git_service_error_count: 0,
    approval_ready: true,
    repair_session_ready_for_candidate_approval: false,
    repair_session_ready_for_platform_promotion: false,
    review_merged: false,
    read_model_published: false,
    next_artifact: "owner/operator repair before promotion",
  },
  workflow: {
    stage: "repair_required",
    status: "blocked",
    items: [
      {
        id: "active_candidate",
        label: "Active candidate",
        status: "ready",
        artifact_key: "active_idea_to_spec_candidate.json",
        artifact_path: "runs/active_idea_to_spec_candidate.json",
        detail: "active_candidate_ready",
      },
      {
        id: "event_storming_intake",
        label: "Event-storming intake",
        status: "ready",
        artifact_key: "idea_event_storming_intake.json",
        artifact_path: "runs/idea_event_storming_intake.json",
        detail: "ready_for_candidate_graph",
      },
      {
        id: "ontology_seed",
        label: "Ontology-bound seed",
        status: "ready",
        artifact_key: "candidate_spec_graph_seed.json",
        artifact_path: "runs/candidate_spec_graph_seed.json",
        detail: "ready_for_candidate_graph",
      },
      {
        id: "candidate_graph",
        label: "Candidate graph",
        status: "ready",
        artifact_key: "candidate_spec_graph.json",
        artifact_path: "runs/candidate_spec_graph.json",
        detail: "ready_for_pre_sib",
      },
      {
        id: "pre_sib",
        label: "Pre-SIB coherence",
        status: "blocked",
        artifact_key: "pre_sib_coherence_report.json",
        artifact_path: "runs/pre_sib_coherence_report.json",
        detail: "pre_sib_review_required",
      },
      {
        id: "repair_loop",
        label: "Repair loop",
        status: "blocked",
        artifact_key: "candidate_repair_loop_report.json",
        artifact_path: "runs/candidate_repair_loop_report.json",
        detail: "context_required",
      },
      {
        id: "product_repair_rerun_execution",
        label: "Repair rerun execution",
        status: "ready",
        artifact_key: "platform_product_repair_rerun_execution_report.json",
        artifact_path: "runs/platform_product_repair_rerun_execution_report.json",
        detail: "completed",
      },
      {
        id: "product_repair_rerun_publication",
        label: "Repair rerun publication",
        status: "ready",
        artifact_key: "platform_product_repair_rerun_publication_report.json",
        artifact_path: "runs/platform_product_repair_rerun_publication_report.json",
        detail: "published",
      },
      {
        id: "materialization",
        label: "Materialization preview",
        status: "ready",
        artifact_key: "candidate_spec_materialization_report.json",
        artifact_path: "runs/candidate_spec_materialization_report.json",
        detail: "materialized_candidate_review_ready",
      },
      {
        id: "promotion_gate",
        label: "Promotion gate",
        status: "blocked",
        artifact_key: "idea_to_spec_promotion_gate.json",
        artifact_path: "runs/idea_to_spec_promotion_gate.json",
        detail: "idea_to_spec_promotion_blocked",
      },
      {
        id: "candidate_approval",
        label: "Candidate approval",
        status: "ready",
        artifact_key: "candidate_approval_decision.json",
        artifact_path: "runs/candidate_approval_decision.json",
        detail: "candidate_approval_ready",
      },
      {
        id: "platform_promotion_request",
        label: "Platform promotion request",
        status: "ready",
        artifact_key: "graph_repository_promotion_request.json",
        artifact_path: "runs/graph_repository_promotion_request.json",
        detail: "graph-candidate/idea-alpha",
      },
      {
        id: "git_service_execution",
        label: "Git Service execution",
        status: "dry_run",
        artifact_key: "git_service_promotion_execution_report.json",
        artifact_path: "runs/git_service_promotion_execution_report.json",
        detail: "open_review_dry_run",
      },
      {
        id: "review_status",
        label: "Review status",
        status: "review_required",
        artifact_key: "graph_repository_review_status_report.json",
        artifact_path: "runs/graph_repository_review_status_report.json",
        detail: "open",
      },
      {
        id: "read_model_publication",
        label: "Read-model publication",
        status: "review_required",
        artifact_key: "graph_repository_publish_read_model_report.json",
        artifact_path: "runs/graph_repository_publish_read_model_report.json",
        detail: null,
      },
    ],
    next_handoff: {
      kind: "operator_repair_review",
      label: "Resolve context-required repairs before promotion",
      status: "blocked",
      artifact_key: "promotion_gate",
      artifact_path: "runs/idea_to_spec_promotion_gate.json",
      command_template: null,
      authority_boundary: "operator_only",
    },
  },
  intake: {
    available: true,
    active_frame: {
      project: "DemoCalculator",
      ontology_refs: ["ontology://specgraph-core"],
      domain_refs: ["domain.calculator"],
      context_refs: ["context.idea_to_spec"],
    },
    summary: {
      actor_count: 1,
      domain_event_count: 1,
      command_count: 1,
      policy_count: 1,
      external_system_count: 0,
      constraint_count: 1,
      vocabulary_question_count: 1,
      context_completion_question_count: 0,
    },
  },
  ontology_seed: {
    available: true,
    source_ref: "product://demo-calculator/candidate-spec-graph-seed",
    contract_ref: "specgraph.idea-to-spec.candidate-spec-graph-seed.v0.1",
    generation_contract_ref:
      "specgraph.idea-to-spec.ontology-bound-candidate-graph-seed.v0.1",
    readiness: {
      ready: true,
      review_state: "ready_for_candidate_graph",
      blocked_by: [],
      next_artifact: null,
    },
    summary: {
      status: "ready_for_candidate_graph",
      node_count: 2,
      edge_count: 1,
      ontology_binding_count: 5,
      ontology_gap_count: 2,
      finding_count: 0,
    },
    ontology: {
      id: "org.0al.specgraph.core",
      namespace: "sgcore",
      version: "0.1.0",
      source_ref: "ontology/packages/specgraph-core/generated/ontology.normalized.json",
      source_digest: "sha256:fixture",
      class_count: 14,
      relation_count: 16,
    },
    bindings: [
      {
        term: "Spec",
        ontology_ref: "ontology://org.0al.specgraph.core/0.1.0/classes/Spec",
        binding_kind: "core_type",
        authority: "ontology_ir",
        reason: "Candidate product boundary maps to a proposed Spec.",
      },
      {
        term: "Node",
        ontology_ref: "ontology://org.0al.specgraph.core/0.1.0/classes/Node",
        binding_kind: "core_type",
        authority: "ontology_ir",
        reason: "Each generated candidate item is represented as a SpecGraph node.",
      },
      {
        term: "Requirement",
        ontology_ref:
          "ontology://org.0al.specgraph.core/0.1.0/classes/Requirement",
        binding_kind: "core_type",
        authority: "ontology_ir",
        reason: "Commands and constraints become proposed requirements.",
      },
    ],
    gaps: [
      {
        id: "ontology-gap.numeric-input",
        kind: "ontology_gap",
        term: "Numeric Input",
        source_ref: "command.enter_digit",
        source_kind: "command",
        suggested_action: "confirm_bind_or_promote_domain_term",
        blocks_candidate_graph: false,
        statement:
          "Confirm whether `Numeric Input` should bind to an existing ontology term or remain a project-local domain term.",
      },
      {
        id: "ontology-gap.operation",
        kind: "ontology_gap",
        term: "Operation",
        source_ref: "question.operation",
        source_kind: "vocabulary_question",
        suggested_action: "confirm_bind_or_promote_domain_term",
        blocks_candidate_graph: false,
        statement:
          "Confirm whether `Operation` should bind to an existing ontology term or remain a project-local domain term.",
      },
    ],
    findings: [],
    privacy_boundary: {
      raw_intent_text_published: false,
      raw_prompt_published: false,
      raw_model_output_published: false,
    },
  },
  candidate_graph: {
    available: true,
    active_frame: {
      project: "DemoCalculator",
      ontology_refs: ["ontology://specgraph-core"],
      domain_refs: ["domain.calculator"],
      context_refs: ["context.idea_to_spec"],
    },
    summary: {
      node_count: 2,
      edge_count: 1,
      requirement_count: 2,
      acceptance_criteria_count: 1,
      claim_count: 1,
      gap_count: 1,
    },
    pre_sib_readiness: { ready: true, review_state: "ready_for_pre_sib" },
    nodes: [
      {
        id: "candidate-spec.calculator-product",
        title: "Calculator Product",
        kind: "product_boundary",
        ontology_refs: ["ontology://specgraph-core#Spec"],
        requirement_count: 1,
        acceptance_criteria_count: 1,
        claim_count: 1,
        gap_count: 0,
      },
      {
        id: "candidate-spec.numeric-input",
        title: "Numeric Input",
        kind: "feature",
        ontology_refs: [],
        requirement_count: 1,
        acceptance_criteria_count: 0,
        claim_count: 0,
        gap_count: 1,
      },
    ],
  },
  pre_sib: {
    available: true,
    readiness: {
      ready: false,
      review_state: "pre_sib_review_required",
      blocked_by: ["pre_sib_ontology_coverage_gap"],
    },
    metrics: {
      node_count: 2,
      edge_count: 1,
      orphan_node_count: 0,
      ontology_coverage_ratio: 0.5,
    },
    findings: [
      {
        finding_id: "pre_sib_ontology_coverage_gap",
        severity: "review_required",
        message: "Every candidate node should carry ontology refs.",
        source_ref: "runs/pre_sib_coherence_report.json",
      },
    ],
  },
  repair_loop: {
    available: true,
    readiness: {
      ready: true,
      review_state: "repair_preview_ready",
      next_artifact: "runs/idea_to_spec_workspace_bundle.json",
    },
    summary: {
      status: "repair_preview_ready",
      action_count: 2,
      applied_action_count: 1,
      context_required_count: 1,
    },
    metric_delta_projection: {
      delta: {
        edge_count: 1,
        acceptance_criteria_count: 1,
      },
    },
    actions: [
      {
        id: "repair.add-ac.req-input-digits",
        kind: "add_acceptance_criterion",
        status: "applied_to_preview",
        target_ref: "req.input.digits",
        rationale: "Add a reviewable placeholder acceptance criterion.",
        source_findings: ["pre_sib_acceptance_criteria_gap"],
      },
      {
        id: "repair.ontology-gap.candidate-spec-numeric-input",
        kind: "add_ontology_gap",
        status: "requires_context",
        target_ref: "candidate-spec.numeric-input",
        rationale: "Ontology refs need owner context.",
        source_findings: ["pre_sib_ontology_coverage_gap"],
      },
    ],
  },
  repair_session: {
    available: true,
    source_mode: "journal",
    readiness: {
      ready: true,
      review_state: "repair_session_journal_ready",
      blocked_by: [],
      next_artifact: "SpecSpace product repair workspace",
    },
    summary: {
      status: "repair_session_journal_ready",
      candidate_id: "team-decision-log",
      workflow_lane: "product_idea_to_spec",
      source_artifact_count: 8,
      accepted_answer_count: 1,
      ontology_decision_count: 1,
      resolved_ontology_gap_count: 1,
      unresolved_ontology_gap_count: 7,
      ready_for_candidate_approval: false,
      finding_count: 0,
    },
    session: {
      session_id: "repair-session.team-decision-log",
      candidate_id: "team-decision-log",
      workflow_lane: "product_idea_to_spec",
      workspace_route: "/team-decision-log",
      target_repository_role: "product_spec_workspace",
      governance_profile: "product_workspace",
      operator_ref: "operator://workspace-owner",
    },
    readiness_impact: {
      ready_for_candidate_approval: false,
      ready_for_platform_promotion: false,
      intermediate_artifacts_ready: true,
      candidate_quality_review_state: "candidate_quality_partially_improved",
      promotion_gate_review_state: "idea_to_spec_promotion_blocked",
      active_candidate_review_state: "active_candidate_review_required",
      resolved_ontology_gap_count: 1,
      unresolved_ontology_gap_count: 7,
      rerun_removed_gap_count: 1,
      clarification_request_count: 1,
      accepted_answer_count: 1,
      ontology_decision_count: 1,
      promotion_path_count: 0,
      blocked_by: ["repair_context_required", "unresolved_ontology_gaps"],
      platform_promotion_blocked_by: ["candidate_not_ready_for_approval"],
    },
    stages: [
      {
        index: 1,
        stage: "active_candidate",
        artifact_kind: "active_idea_to_spec_candidate",
        source_ref: "runs/active_idea_to_spec_candidate.json",
        ready: false,
        review_state: "active_candidate_review_required",
        status: "active_candidate_review_required",
        blocked_by: ["promotion_gate_not_ready"],
        next_artifact: "repair active candidate source before public handoff",
      },
      {
        index: 8,
        stage: "promotion_gate",
        artifact_kind: "idea_to_spec_promotion_gate",
        source_ref: "runs/idea_to_spec_promotion_gate.json",
        ready: false,
        review_state: "idea_to_spec_promotion_blocked",
        status: "idea_to_spec_promotion_blocked",
        blocked_by: ["repair_context_required"],
        next_artifact: "owner/operator repair before promotion",
      },
    ],
    open_blockers: [
      { kind: "repair_session", id: "repair_context_required" },
      { kind: "repair_session", id: "unresolved_ontology_gaps" },
      { kind: "platform_promotion", id: "candidate_not_ready_for_approval" },
    ],
    accepted_answers: [
      {
        request_id: "clarification.candidate-gap.ontology-gap-numeric-input",
        answer_kind: "propose_project_local_term",
        status: "accepted_for_candidate",
        request_kind: "ontology_gap",
        target_artifact: "runs/candidate_spec_graph.json",
        target_ref: "candidate-spec.numeric-input.gaps.ontology-gap.numeric-input",
        terms: ["Numeric Input"],
        term_scope: "project_local",
      },
    ],
    ontology_decisions: [
      {
        id: "product-ontology-decision.numeric-input.0",
        decision_type: "propose_project_local_term",
        status: "accepted_for_candidate_preview",
        term: "Numeric Input",
        ontology_ref: null,
        alias_of: null,
        target_ref: "candidate-spec.numeric-input.gaps.ontology-gap.numeric-input",
        request_id: "clarification.candidate-gap.ontology-gap-numeric-input",
        materialization_intent: "rerun_overlay_only",
      },
    ],
    rerun_overlay: {
      source_ref: "runs/idea_to_spec_answer_rerun_input.json",
      summary: {
        status: "rerun_input_ready",
        ontology_decision_source: "product_ontology_gap_review_decisions",
        ontology_decision_count: 1,
        project_local_term_count: 1,
      },
    },
    preview_refs: {
      rerun_preview: {
        source_ref: "runs/idea_to_spec_rerun_preview.json",
        summary: {
          status: "rerun_preview_ready",
          candidate_quality_review_state: "candidate_quality_partially_improved",
          resolved_ontology_gap_count: 1,
          unresolved_ontology_gap_count: 7,
        },
      },
      rerun_materialization: {
        source_ref: "runs/idea_to_spec_rerun_materialization.json",
        summary: {
          status: "rerun_materialization_ready",
          removed_gap_count: 1,
          resolved_ontology_gap_count: 1,
          unresolved_ontology_gap_count: 7,
        },
      },
    },
    findings: [],
    authority_boundary: {
      may_execute_prompt_agent: false,
      may_apply_answers_to_source_artifacts: false,
      may_apply_decisions_to_source_artifacts: false,
      may_mutate_candidate_source_artifacts: false,
      may_mutate_canonical_specs: false,
      may_write_ontology_package: false,
      may_write_ontology_lockfile: false,
      may_accept_ontology_terms: false,
      may_mark_candidate_graph_accepted: false,
      may_create_branch_or_commit: false,
      may_open_pull_request: false,
      may_publish_read_model: false,
    },
    privacy_boundary: {
      raw_idea_text_published: false,
      raw_prompt_published: false,
      raw_model_output_published: false,
      raw_operator_note_published: false,
      static_flags_are_asserted_invariants: true,
      redaction_enforced_by: "recursive_public_safe_field_filter",
    },
    action_boundary: {
      inspect_only: true,
      acknowledge_only: true,
      may_apply_answers: false,
      may_apply_decisions: false,
      may_mutate_candidate_artifacts: false,
      may_accept_ontology_terms: false,
      may_write_ontology_package: false,
      may_create_branch_or_commit: false,
    },
  },
  repair_review: {
    available: true,
    clarification_requests: {
      available: true,
      readiness: {
        ready: false,
        review_state: "clarification_required",
        blocked_by: ["clarification.candidate-gap.ontology-gap-numeric-input"],
        next_artifact: null,
      },
      summary: {
        total: 1,
        by_kind: { ontology_gap: 1 },
      },
      requests: [
        {
          id: "clarification.candidate-gap.ontology-gap-numeric-input",
          kind: "ontology_gap",
          severity: "review_required",
          status: "open",
          target_ref: "candidate-spec.numeric-input.gaps.ontology-gap.numeric-input",
          question: "Should Numeric Input bind, alias, remain local, or be rejected?",
          suggested_actions: [
            "bind_existing_term",
            "alias",
            "propose_project_local_term",
            "reject",
            "defer",
          ],
        },
      ],
      request_count: 1,
      ontology_gap_request_count: 1,
    },
    clarification_answers: {
      available: true,
      readiness: {
        ready: true,
        review_state: "answers_ready_for_rerun",
        blocked_by: [],
        next_artifact: null,
      },
      summary: {
        answer_count: 1,
        accepted_answer_count: 1,
      },
      accepted_answers: [
        {
          request_id: "clarification.candidate-gap.ontology-gap-numeric-input",
          answer_kind: "propose_project_local_term",
          status: "accepted_for_candidate",
          request_kind: "ontology_gap",
          target_artifact: "runs/candidate_spec_graph.json",
          target_ref: "candidate-spec.numeric-input.gaps.ontology-gap.numeric-input",
          terms: ["Numeric Input"],
          term_scope: "project_local",
        },
      ],
      answer_count: 1,
      unresolved_blocking_count: 0,
    },
    ontology_decisions: {
      available: true,
      readiness: {
        ready: true,
        review_state: "ontology_gap_decisions_ready",
        blocked_by: [],
        next_artifact: null,
      },
      summary: {
        decision_count: 1,
        decision_counts: { propose_project_local_term: 1 },
      },
      decisions: [
        {
          id: "product-ontology-decision.numeric-input.0",
          decision_type: "propose_project_local_term",
          status: "accepted_for_candidate_preview",
          term: "Numeric Input",
          ontology_ref: null,
          alias_of: null,
          target_ref: "candidate-spec.numeric-input.gaps.ontology-gap.numeric-input",
          request_id: "clarification.candidate-gap.ontology-gap-numeric-input",
          materialization_intent: "rerun_overlay_only",
        },
      ],
      decision_count: 1,
    },
    rerun_input: {
      available: true,
      readiness: {
        ready: true,
        review_state: "rerun_input_ready",
        blocked_by: [],
        next_artifact: null,
      },
      summary: {
        ontology_decision_source: "product_ontology_gap_review_decisions",
        ontology_decision_count: 1,
      },
      ontology_hint_counts: {
        term_binding_count: 0,
        alias_count: 0,
        project_local_term_count: 1,
        rejected_term_count: 0,
        deferred_term_count: 0,
      },
    },
    rerun_preview: {
      available: true,
      readiness: {
        ready: true,
        review_state: "rerun_preview_ready",
        blocked_by: [],
        next_artifact: null,
      },
      summary: {
        candidate_quality_review_state: "candidate_quality_improved",
        resolved_ontology_gap_count: 1,
        unresolved_ontology_gap_count: 0,
      },
      candidate_quality_preview: {
        review_state: "candidate_quality_improved",
        ontology_gap_state: "all_preview_resolved",
        resolved_ontology_gap_count: 1,
        unresolved_ontology_gap_count: 0,
      },
      resolved_gaps: [
        {
          gap_id: "ontology-gap.numeric-input",
          node_id: "candidate-spec.numeric-input",
          term: "Numeric Input",
          source_ref: "command.enter_digit",
          decision: "project_local_term",
          target_ref: "candidate-spec.numeric-input.gaps.ontology-gap.numeric-input",
        },
      ],
      unresolved_ontology_gap_count: 0,
    },
    rerun_materialization: {
      available: true,
      readiness: {
        ready: true,
        review_state: "rerun_materialization_ready",
        blocked_by: [],
        next_artifact: null,
      },
      summary: {
        removed_gap_count: 1,
      },
      delta: {
        removed_gap_ids: ["ontology-gap.numeric-input"],
        unresolved_ontology_gap_ids: [],
        resolved_ontology_gap_count: 1,
        unresolved_ontology_gap_count: 0,
      },
    },
    platform_execution: {
      available: true,
      execution: {
        available: true,
        ok: true,
        dry_run: false,
        status: "completed",
        error_count: 0,
        output_artifact_count: 2,
        rerun_report_digest: "sha256:rerun",
        repair_session_digest: "sha256:session",
        diagnostic_count: 0,
        operations: [
          {
            name: "execute_specgraph_requested_rerun",
            status: "succeeded",
            reason: "SpecGraph requested rerun target executed",
            evidence: ["product-workspace-requested-repair-draft-rerun"],
          },
        ],
        output_artifacts: [
          {
            key: "rerun_report",
            path: "runs/specspace_repair_draft_rerun_report.json",
            present: true,
            artifact_kind: "specspace_repair_draft_rerun_report",
            contract_ref:
              "specgraph.idea-to-spec.specspace-repair-draft-rerun.v0.1",
            status: "repair_draft_rerun_ready",
            ready: true,
            sha256: "sha256:rerun",
          },
          {
            key: "repair_session",
            path: "runs/idea_to_spec_repair_session.json",
            present: true,
            artifact_kind: "idea_to_spec_repair_session_journal",
            contract_ref: "specgraph.idea-to-spec.repair-session-journal.v0.1",
            status: "repair_session_journal_ready",
            ready: true,
            sha256: "sha256:session",
          },
        ],
      },
      publication: {
        available: true,
        ok: true,
        dry_run: false,
        status: "published",
        error_count: 0,
        published_artifact_count: 2,
        missing_artifact_count: 0,
        manifest_path: "dist/specgraph-public/artifact_manifest.json",
        manifest_present: true,
        published_artifacts: [
          "runs/idea_to_spec_repair_session.json",
          "runs/specspace_repair_draft_rerun_report.json",
        ],
        missing_artifacts: [],
        diagnostic_count: 0,
      },
      action_boundary: {
        inspect_only: true,
        acknowledge_only: true,
        may_execute_platform_adapter: false,
        may_run_specgraph_make_target: false,
        may_publish_bundle: false,
        may_create_branch_or_commit: false,
        may_open_pull_request: false,
        may_write_ontology_package: false,
        may_accept_ontology_terms: false,
        may_mutate_canonical_specs: false,
      },
    },
    action_boundary: {
      inspect_only: true,
      acknowledge_only: true,
      may_apply_answers: false,
      may_apply_decisions: false,
      may_mutate_candidate_artifacts: false,
      may_accept_ontology_terms: false,
      may_write_ontology_package: false,
      may_create_branch_or_commit: false,
    },
  },
  materialization: {
    available: true,
    readiness: {
      ready: true,
      review_state: "materialized_candidate_review_ready",
      next_artifact: "Platform graph-repository promotion-request",
    },
    summary: {
      status: "materialized_candidate_review_ready",
      materialized_file_count: 2,
      candidate_node_count: 2,
      finding_count: 0,
    },
    materialization_source: "repair_loop_preview",
    files: [
      {
        candidate_node_id: "candidate-spec.calculator-product",
        materialized_id: "CANDIDATE-CANDIDATE-SPEC-CALCULATOR-PRODUCT",
        path: "runs/materialized_candidate_specs/CANDIDATE-CANDIDATE-SPEC-CALCULATOR-PRODUCT.yaml",
        promotion_path: "runs/materialized_candidate_specs/CANDIDATE-CANDIDATE-SPEC-CALCULATOR-PRODUCT.yaml",
      },
      {
        candidate_node_id: "candidate-spec.numeric-input",
        materialized_id: "CANDIDATE-CANDIDATE-SPEC-NUMERIC-INPUT",
        path: "runs/materialized_candidate_specs/CANDIDATE-CANDIDATE-SPEC-NUMERIC-INPUT.yaml",
        promotion_path: "runs/materialized_candidate_specs/CANDIDATE-CANDIDATE-SPEC-NUMERIC-INPUT.yaml",
      },
    ],
    promotion_request: {
      path_argument: "--path",
      platform_artifact_kind: "platform_graph_repository_promotion_request",
      paths: [
        "runs/materialized_candidate_specs/CANDIDATE-CANDIDATE-SPEC-CALCULATOR-PRODUCT.yaml",
        "runs/materialized_candidate_specs/CANDIDATE-CANDIDATE-SPEC-NUMERIC-INPUT.yaml",
      ],
    },
  },
  promotion_gate: {
    available: true,
    readiness: {
      ready: false,
      review_state: "idea_to_spec_promotion_blocked",
      blocked_by: ["repair_context_required"],
      next_artifact: "owner/operator repair before promotion",
    },
    summary: {
      status: "idea_to_spec_promotion_blocked",
      finding_count: 1,
      warning_count: 0,
      promotion_path_count: 0,
      materialized_file_count: 2,
    },
    metric_snapshot: {
      pre_sib: {
        ontology_coverage_ratio: 0.5,
      },
      materialized_file_count: 2,
      promotion_path_count: 0,
    },
    findings: [
      {
        finding_id: "repair_context_required",
        severity: "review_required",
        message: "Owner/operator context is still required.",
        source_ref: "idea_to_spec_promotion_gate",
      },
    ],
    promotion_request: {
      path_argument: "--path",
      platform_artifact_kind: "platform_graph_repository_promotion_request",
      paths: [],
    },
  },
  controlled_promotion: {
    available: true,
    candidate_approval: {
      available: true,
      ready: true,
      decision_state: "approved",
      requested_state: "approved",
      review_state: "candidate_approval_ready",
      operator_ref: "operator://workspace-owner",
      reason: "Approve review-ready product workspace candidate.",
      candidate_id: "idea-alpha",
      promotion_paths: [
        "runs/materialized_candidate_specs/CANDIDATE-CANDIDATE-SPEC-CALCULATOR-PRODUCT.yaml",
        "runs/materialized_candidate_specs/CANDIDATE-CANDIDATE-SPEC-NUMERIC-INPUT.yaml",
      ],
      blocked_by: [],
    },
    platform_request: {
      available: true,
      ok: true,
      candidate_id: "idea-alpha",
      candidate_branch: "graph-candidate/idea-alpha",
      commit_paths: [
        "runs/materialized_candidate_specs/CANDIDATE-CANDIDATE-SPEC-CALCULATOR-PRODUCT.yaml",
        "runs/materialized_candidate_specs/CANDIDATE-CANDIDATE-SPEC-NUMERIC-INPUT.yaml",
      ],
      requested_operations: [
        "prepare_branch",
        "create_commit",
        "open_review",
      ],
      review: {
        title: "Add candidate spec graph",
        base_branch: "main",
      },
      summary: {
        error_count: 0,
        commit_path_count: 2,
        promotion_ready: true,
      },
    },
    git_service_execution: {
      available: true,
      ok: true,
      dry_run: false,
      open_review_dry_run: true,
      candidate_id: "idea-alpha",
      candidate_ref: "graph-candidate/idea-alpha",
      workspace_dir: ".platform/candidates/idea-alpha-worktree",
      operation_count: 3,
      completed_operation_count: 3,
      error_count: 0,
      copied_file_count: 1,
      operations: [
        {
          name: "prepare_worktree",
          status: "succeeded",
          request_artifact_kind: "platform_git_service_prepare_worktree_request",
          response_artifact_kind: "platform_git_service_prepare_worktree_response",
          report_ref:
            ".platform/candidates/idea-alpha-worktree/.platform/graph_repository_worktree_prepare_report.json",
          diagnostic_count: 0,
        },
        {
          name: "commit_candidate",
          status: "succeeded",
          request_artifact_kind: "platform_git_service_commit_candidate_request",
          response_artifact_kind: "platform_git_service_commit_candidate_response",
          report_ref:
            ".platform/candidates/idea-alpha-worktree/.platform/graph_repository_review_commit_report.json",
          diagnostic_count: 0,
        },
        {
          name: "open_review",
          status: "dry_run",
          request_artifact_kind: "platform_git_service_open_review_request",
          response_artifact_kind: "platform_git_service_open_review_response",
          report_ref: null,
          diagnostic_count: 0,
        },
      ],
      report_refs: {
        prepare_worktree:
          ".platform/candidates/idea-alpha-worktree/.platform/graph_repository_worktree_prepare_report.json",
        commit_candidate:
          ".platform/candidates/idea-alpha-worktree/.platform/graph_repository_review_commit_report.json",
      },
    },
    review_status: {
      available: true,
      ok: true,
      review_state: "open",
      review_decision: "APPROVED",
      review_url: "https://github.com/example/product/pull/12",
      review_merged: false,
      error_count: 0,
    },
    read_model_publication: {
      available: true,
      ok: true,
      dry_run: false,
      review_state: "open",
      manifest: "published-read-model/artifact_manifest.json",
      published: false,
      file_count: 0,
      error_count: 0,
    },
    promotion_finalization: {
      available: true,
      ok: true,
      dry_run: false,
      review_state: "open",
      read_model_published: false,
      operation_count: 1,
      completed_operation_count: 1,
      error_count: 0,
      operations: [
        {
          name: "review_status",
          status: "succeeded",
          request_artifact_kind: "platform_git_service_review_status_request",
          response_artifact_kind: "platform_git_service_review_status_response",
          report_ref: ".platform/graph_repository_review_status_report.json",
          diagnostic_count: 0,
        },
      ],
      report_refs: {
        review_status: ".platform/graph_repository_review_status_report.json",
      },
    },
    action_boundary: {
      inspect_only: true,
      acknowledge_only: true,
      may_execute_git_service: false,
      may_create_branch_or_commit: false,
      may_merge_review: false,
      may_mutate_specs: false,
    },
  },
  artifacts: {
    event_storming_intake: {
      available: true,
      path: "runs/idea_event_storming_intake.json",
      artifact_kind: "idea_event_storming_intake",
      status: "ready_for_candidate_graph",
      proposal_id: "0149",
      contract_ref: "specgraph.idea-to-spec.event-storming-intake.v0.1",
    },
    ontology_seed: {
      available: true,
      path: "runs/candidate_spec_graph_seed.json",
      artifact_kind: "candidate_spec_graph_seed",
      status: "ready_for_candidate_graph",
      proposal_id: "0159",
      contract_ref: "specgraph.idea-to-spec.candidate-spec-graph-seed.v0.1",
    },
    candidate_graph: {
      available: true,
      path: "runs/candidate_spec_graph.json",
      artifact_kind: "candidate_spec_graph",
      status: "ready_for_pre_sib",
      proposal_id: "0150",
      contract_ref: "specgraph.idea-to-spec.candidate-spec-graph.v0.1",
    },
    pre_sib: {
      available: true,
      path: "runs/pre_sib_coherence_report.json",
      artifact_kind: "pre_sib_coherence_report",
      status: "pre_sib_review_required",
      proposal_id: "0151",
      contract_ref: "specgraph.idea-to-spec.pre-sib-coherence-report.v0.1",
    },
    repair_loop: {
      available: true,
      path: "runs/candidate_repair_loop_report.json",
      artifact_kind: "candidate_repair_loop_report",
      status: "repair_preview_ready",
      proposal_id: "0152",
      contract_ref: "specgraph.idea-to-spec.candidate-repair-loop.v0.1",
    },
    clarification_requests: {
      available: true,
      path: "runs/idea_to_spec_clarification_requests.json",
      artifact_kind: "idea_to_spec_clarification_requests",
      status: "clarification_required",
      proposal_id: "0163",
      contract_ref: "specgraph.idea-to-spec.clarification-requests.v0.1",
    },
    clarification_answers: {
      available: true,
      path: "runs/idea_to_spec_clarification_answers.json",
      artifact_kind: "idea_to_spec_clarification_answers",
      status: "answers_ready_for_rerun",
      proposal_id: "0164",
      contract_ref: "specgraph.idea-to-spec.clarification-answers.v0.1",
    },
    ontology_decisions: {
      available: true,
      path: "runs/product_ontology_gap_review_decisions.json",
      artifact_kind: "product_ontology_gap_review_decisions",
      status: "ontology_gap_decisions_ready",
      proposal_id: "0168",
      contract_ref: "specgraph.product-ontology.gap-review-decisions.v0.1",
    },
    rerun_input: {
      available: true,
      path: "runs/idea_to_spec_answer_rerun_input.json",
      artifact_kind: "idea_to_spec_answer_rerun_input",
      status: "rerun_input_ready",
      proposal_id: "0169",
      contract_ref: "specgraph.idea-to-spec.answer-rerun-input.v0.1",
    },
    rerun_preview: {
      available: true,
      path: "runs/idea_to_spec_rerun_preview.json",
      artifact_kind: "idea_to_spec_rerun_preview",
      status: "rerun_preview_ready",
      proposal_id: "0169",
      contract_ref: "specgraph.idea-to-spec.rerun-preview.v0.1",
    },
    rerun_materialization: {
      available: true,
      path: "runs/idea_to_spec_rerun_materialization.json",
      artifact_kind: "idea_to_spec_rerun_materialization",
      status: "rerun_materialization_ready",
      proposal_id: "0167",
      contract_ref: "specgraph.idea-to-spec.rerun-materialization.v0.1",
    },
    product_repair_rerun_execution: {
      available: true,
      path: "runs/platform_product_repair_rerun_execution_report.json",
      artifact_kind: "platform_product_repair_rerun_execution_report",
      status: "completed",
      proposal_id: null,
      contract_ref: null,
    },
    product_repair_rerun_publication: {
      available: true,
      path: "runs/platform_product_repair_rerun_publication_report.json",
      artifact_kind: "platform_product_repair_rerun_publication_report",
      status: "published",
      proposal_id: null,
      contract_ref: null,
    },
    materialization: {
      available: true,
      path: "runs/candidate_spec_materialization_report.json",
      artifact_kind: "candidate_spec_materialization_report",
      status: "materialized_candidate_review_ready",
      proposal_id: "0153",
      contract_ref: "specgraph.idea-to-spec.candidate-spec-materialization.v0.1",
    },
    promotion_gate: {
      available: true,
      path: "runs/idea_to_spec_promotion_gate.json",
      artifact_kind: "idea_to_spec_promotion_gate",
      status: "idea_to_spec_promotion_blocked",
      proposal_id: "0154",
      contract_ref: "specgraph.idea-to-spec.promotion-gate.v0.1",
    },
    candidate_approval: {
      available: true,
      path: "runs/candidate_approval_decision.json",
      artifact_kind: "candidate_approval_decision",
      status: "candidate_approval_ready",
      proposal_id: "0157",
      contract_ref: "specgraph.idea-to-spec.candidate-approval-decision.v0.1",
    },
    platform_promotion_request: {
      available: true,
      path: "runs/graph_repository_promotion_request.json",
      artifact_kind: "platform_graph_repository_promotion_request",
      status: null,
      proposal_id: null,
      contract_ref: null,
    },
    git_service_execution: {
      available: true,
      path: "runs/git_service_promotion_execution_report.json",
      artifact_kind: "platform_git_service_promotion_execution_report",
      status: null,
      proposal_id: null,
      contract_ref: null,
    },
    review_status: {
      available: true,
      path: "runs/graph_repository_review_status_report.json",
      artifact_kind: "platform_graph_repository_review_status_report",
      status: null,
      proposal_id: null,
      contract_ref: null,
    },
    read_model_publication: {
      available: true,
      path: "runs/graph_repository_publish_read_model_report.json",
      artifact_kind: "platform_graph_repository_publish_read_model_report",
      status: null,
      proposal_id: null,
      contract_ref: null,
    },
    promotion_finalization: {
      available: true,
      path: "runs/git_service_promotion_finalization_report.json",
      artifact_kind: "platform_git_service_promotion_finalization_report",
      status: null,
      proposal_id: null,
      contract_ref: null,
    },
  },
  display_limits: {
    nodes: 40,
    findings: 40,
    repair_actions: 40,
    ontology_bindings: 20,
    ontology_gaps: 40,
    clarification_requests: 40,
    ontology_decisions: 40,
    resolved_gaps: 40,
    materialized_files: 40,
    git_service_operations: 20,
  },
  authority_boundary: {
    idea_to_spec_workspace_is_authority: false,
    may_execute_prompt_agent: false,
    may_mutate_candidate_source_artifacts: false,
    may_mutate_canonical_specs: false,
    may_write_ontology_package: false,
    may_create_branch_or_commit: false,
    may_execute_git_service_operation: false,
    may_mark_candidate_accepted: false,
  },
};
