export const workbench = {
  api_version: "v1",
  artifact_kind: "specspace_ontology_workbench",
  schema_version: 1,
  generated_at: "2026-06-20T00:00:00+00:00",
  read_only: true,
  canonical_mutations_allowed: false,
  tracked_artifacts_written: false,
  source: { provider: "http", read_only: true },
  summary: {
    status: "ready",
    term_count: 3,
    relation_count: 1,
    domain_count: 1,
    package_count: 1,
    gap_count: 1,
    gap_group_count: 1,
    compliance_spec_count: 1,
    compliance_finding_count: 1,
    write_gate_finding_count: 2,
    specauthor_invocation_finding_count: 0,
    owner_decision_review_count: 1,
    owner_decision_importable_count: 1,
    legacy_spec_count: 1,
    legacy_review_required_spec_count: 1,
    legacy_small_pr_batch_count: 1,
    missing_artifact_count: 0,
    next_gap: "review_legacy_spec_backfill_batches",
  },
  package: {
    package_id: "org.0al.specgraph.core",
    namespace: "sgcore",
    version: "0.1.0",
    package_ref: "org.0al.specgraph.core@0.1.0",
    authority_class: "fixture",
    materialized_ir: "ontology/specgraph-core/ontology.normalized.json",
  },
  normalized_ir: {
    available: true,
    id: "org.0al.specgraph.core",
    namespace: "sgcore",
    version: "0.1.0",
    classes: [
      {
        id: "SpecGraph",
        fqid: "sgcore:SpecGraph",
        uri: "ontology://org.0al.specgraph.core/classes/SpecGraph",
        description: "Executable product ontology.",
      },
    ],
    relations: [
      {
        id: "definesRequirement",
        fqid: "sgcore:definesRequirement",
        domain: "sgcore:Spec",
        range: "sgcore:Requirement",
      },
    ],
  },
  domains: [],
  layers: {
    known_layers: ["objective", "mechanics", "execution", "meta", "multi_agent"],
    rows: [
      {
        layer: "objective",
        package_entry_count: 1,
        gap_count: 0,
        diff_change_count: 0,
        total_count: 1,
      },
      {
        layer: "mechanics",
        package_entry_count: 1,
        gap_count: 0,
        diff_change_count: 0,
        total_count: 1,
      },
      {
        layer: "meta",
        package_entry_count: 0,
        gap_count: 1,
        diff_change_count: 1,
        total_count: 2,
      },
    ],
    summary: {
      known_layer_count: 5,
      used_layer_count: 3,
      package_layered_entry_count: 2,
      package_unlayered_entry_count: 2,
      gap_unassigned_layer_count: 0,
      diff_unassigned_change_count: 0,
    },
    unassigned: {
      gap_count: 0,
      diff_change_count: 0,
      diff_refs: [],
    },
  },
  applicability: {
    summary: {
      profile_count: 1,
      assumption_count: 2,
      invalidation_trigger_count: 2,
      used_layer_count: 3,
      used_layers: ["mechanics", "execution", "meta"],
      layer_counts: { mechanics: 1, execution: 1, meta: 2 },
    },
    profiles: [
      {
        package_id: "org.0al.specgraph.core",
        package_ref: "org.0al.specgraph.core@0.1.0",
        status: "declared",
        applies_to: {
          domains: ["specgraph_core"],
          lifecycle_phases: ["draft_spec_authoring", "ontology_import_review"],
          agent_types: ["SpecAuthorAgent", "SpecGraphSupervisor"],
        },
        excludes: { domains: ["unrelated_product_domain"] },
        assumptions: [
          {
            id: "project_local_authority",
            layer: "meta",
            text: "SpecGraph core ontology packages remain project-local.",
          },
          {
            id: "human_review_required",
            layer: "execution",
            text: "Generated ontology changes require human review before specs change.",
          },
        ],
        invalidation_triggers: [
          {
            id: "ontology_layer_contract_changed",
            layer: "meta",
            text: "Re-review when ontology layer semantics change.",
          },
          {
            id: "specgraph_core_vocabulary_changed",
            layer: "mechanics",
            text: "Re-review when core SpecGraph vocabulary changes.",
          },
        ],
        summary: {
          assumption_count: 2,
          invalidation_trigger_count: 2,
          used_layers: ["mechanics", "execution", "meta"],
        },
      },
    ],
  },
  diff_classification: {
    summary: {
      structural_change_count: 1,
      annotation_change_count: 1,
      applicability_change_count: 1,
      total_change_count: 3,
    },
    structural_changes: [{ kind: "classAdded", ref: "sgcore:ClaimCalibration" }],
    annotation_changes: [
      {
        kind: "layerChanged",
        ref: "sgcore:Spec",
        target_kind: "class",
        before: "objective",
        after: "mechanics",
        compatibility: "compatible",
      },
    ],
    applicability_changes: [
      {
        kind: "invalidationTriggerAdded",
        ref: "modelApplicability.invalidationTriggers.specgraph_core_vocabulary_changed",
        compatibility: "compatible",
      },
    ],
  },
  gap_review: {
    summary: { gap_group_count: 1 },
    groups: [
      {
        group_id: "ontology-gap-review-legacy-term-intent",
        gap_kind: "legacy_term",
        gap_key: "legacy_term:intent",
        review_state: "needs_owner_review",
        recommended_owner_action: "review_legacy_term_for_package_draft",
        recommended_route: "ontology_owner_review",
        proposed_term: "Intent",
        source_spec_count: 1,
        affected_generated_artifact_count: 0,
        source_specs: [{ spec_id: "SG-SPEC-0001", term: "intent" }],
      },
    ],
  },
  compliance: {
    summary: { finding_count: 1 },
    entries: [
      {
        spec_id: "SG-SPEC-0001",
        path: "specs/nodes/SG-SPEC-0001.yaml",
        validation_status: "report_only_findings",
        finding_count: 1,
        terms: ["intent"],
        findings: [
          {
            finding_id: "SG-SPEC-0001.gap.intent",
            severity: "warning",
            classification: "unknown_legacy_term",
            term: "intent",
          },
        ],
      },
    ],
  },
  write_gate: {
    summary: { finding_count: 2 },
    would_reject_in_hard_gate: true,
    write_decision: "review_required",
    findings: [
      {
        finding_id: "active_frame_incomplete",
        severity: "review_required",
        message: "active_frame must resolve ontology/domain/context.",
      },
    ],
  },
  specauthor_invocation: {
    available: true,
    summary: {
      status: "ready_for_operator_review",
      finding_count: 0,
      operator_decision_state: "pending_review",
      invocation_contract_ok: true,
      authoring_flow_ok: true,
    },
    invocation: {
      invocation_id: "specauthor-invocation-0146-ready",
      agent_id: "SpecAuthorAgent",
      mode: "draft_authoring",
      prompt_contract_ref: "docs/proposals/0126_specauthor_claim_calibration_prompt_contract.md",
      user_intent_text: "Draft a review-only proposal using existing SpecGraph ontology terms.",
      user_intent_source_ref: "operator://local-intent/0146",
    },
    active_frame: {
      project: "SpecGraph",
      subsystem: "Application.AgentLayer.SpecificationAuthoring",
      agent_layer: "SpecificationAuthoring",
      target_artifact: "Proposal",
      lifecycle_phase: "draft",
      ontology_refs: ["sgcore:Spec"],
      ontology_layer_refs: ["meta"],
      model_applicability_refs: ["org.0al.specgraph.core@0.1.0#modelApplicability"],
      domain_refs: ["domain.specification_authoring"],
      context_refs: ["context.specgraph.agent_layer"],
    },
    model_applicability: {
      package_ref: "org.0al.specgraph.core@0.1.0",
      assumption_refs: [
        "modelApplicability.assumptions.project_local_authority",
        "modelApplicability.assumptions.human_review_required",
      ],
      invalidation_trigger_refs: [
        "modelApplicability.invalidationTriggers.ontology_layer_contract_changed",
        "modelApplicability.invalidationTriggers.specgraph_core_vocabulary_changed",
      ],
    },
    validation_chain: {
      generated_artifact_contract_ok: true,
      write_gate_ok: true,
      write_decision: "allow_graph_write",
      invocation_contract_ok: true,
      invocation_review_state: "ready_for_operator_review",
    },
    operator_decision: {
      decision_state: "pending_review",
      reviewer: null,
      may_execute_prompt_agent: false,
      may_write_ontology_package: false,
      may_mutate_canonical_specs: false,
    },
    findings: [],
  },
  owner_decisions: {
    summary: { review_count: 1 },
    reviews: [
      {
        review_id: "ontology-owner-decision-review-intent",
        decision_id: "ontology-owner-decision-accept-intent",
        decision_state: "accepted",
        review_state: "ready_for_operator_review",
        before_semantic_status: "unknown_legacy_term",
        after_semantic_status: "accepted_term",
        import_recommended: true,
      },
    ],
  },
  legacy_backfill: {
    summary: { small_pr_batch_count: 1 },
    small_pr_batches: [
      {
        batch_id: "legacy-spec-ontology-backfill-batch-001",
        review_state: "ready_for_review",
        recommended_pr_scope: "small_reviewed_terminology_backfill",
        spec_count: 1,
        finding_count: 1,
        writes_ontology_package: false,
        mutates_canonical_specs: false,
        specs: [{ spec_id: "SG-SPEC-0001", unknown_terms: ["intent"] }],
      },
    ],
  },
  artifacts: {
    gap_review_workflow: {
      available: true,
      path: "runs/ontology_gap_review_workflow.json",
      artifact_kind: "ontology_gap_review_workflow",
      schema_version: 1,
      status: "review_required",
    },
    specauthor_invocation: {
      available: true,
      path: "runs/specauthor_invocation_artifact.json",
      artifact_kind: "specauthor_invocation_artifact",
      schema_version: 1,
      status: "ready_for_operator_review",
    },
    specauthor_invocation_contract: {
      available: true,
      path: "runs/specauthor_invocation_artifact_contract_report.json",
      artifact_kind: "specauthor_invocation_artifact_contract_report",
      schema_version: 1,
      status: "ready_for_operator_review",
    },
    specauthor_authoring_flow: {
      available: true,
      path: "runs/specauthor_authoring_flow_report.json",
      artifact_kind: "specauthor_authoring_flow_report",
      schema_version: 1,
      status: "ready_for_operator_review",
    },
  },
  display_limits: { gap_groups: 40 },
  authority_boundary: {
    ontology_workbench_is_authority: false,
    practical_ontology_is_authority: false,
    may_write_ontology_package: false,
    may_update_ontology_lockfile: false,
    may_mutate_canonical_specs: false,
    may_mark_candidate_accepted: false,
    may_import_owner_decision: false,
    may_close_semantic_gate: false,
  },
};
