export const workbench = {
  api_version: "v1",
  artifact_kind: "specspace_ontology_workbench",
  schema_version: 1,
  generated_at: "2026-06-20T00:00:00+00:00",
  read_only: true,
  canonical_mutations_allowed: false,
  tracked_artifacts_written: false,
  source: { provider: "http", read_only: true },
  summary: {
    status: "ready",
    term_count: 3,
    relation_count: 1,
    domain_count: 1,
    package_count: 1,
    gap_count: 1,
    gap_group_count: 1,
    compliance_spec_count: 1,
    compliance_finding_count: 1,
    write_gate_finding_count: 2,
    owner_decision_review_count: 1,
    owner_decision_importable_count: 1,
    legacy_spec_count: 1,
    legacy_review_required_spec_count: 1,
    legacy_small_pr_batch_count: 1,
    missing_artifact_count: 0,
    next_gap: "review_legacy_spec_backfill_batches",
  },
  package: {
    package_id: "org.0al.specgraph.core",
    namespace: "sgcore",
    version: "0.1.0",
    package_ref: "org.0al.specgraph.core@0.1.0",
    authority_class: "fixture",
    materialized_ir: "ontology/specgraph-core/ontology.normalized.json",
  },
  normalized_ir: {
    available: true,
    id: "org.0al.specgraph.core",
    namespace: "sgcore",
    version: "0.1.0",
    classes: [
      {
        id: "SpecGraph",
        fqid: "sgcore:SpecGraph",
        uri: "ontology://org.0al.specgraph.core/classes/SpecGraph",
        description: "Executable product ontology.",
      },
    ],
    relations: [
      {
        id: "definesRequirement",
        fqid: "sgcore:definesRequirement",
        domain: "sgcore:Spec",
        range: "sgcore:Requirement",
      },
    ],
  },
  domains: [],
  layers: {
    known_layers: ["objective", "mechanics", "execution", "meta", "multi_agent"],
    rows: [
      {
        layer: "objective",
        package_entry_count: 1,
        gap_count: 0,
        diff_change_count: 0,
        total_count: 1,
      },
      {
        layer: "mechanics",
        package_entry_count: 1,
        gap_count: 0,
        diff_change_count: 0,
        total_count: 1,
      },
      {
        layer: "meta",
        package_entry_count: 0,
        gap_count: 1,
        diff_change_count: 1,
        total_count: 2,
      },
    ],
    summary: {
      known_layer_count: 5,
      used_layer_count: 3,
      package_layered_entry_count: 2,
      package_unlayered_entry_count: 2,
      gap_unassigned_layer_count: 0,
      diff_unassigned_change_count: 0,
    },
    unassigned: {
      gap_count: 0,
      diff_change_count: 0,
      diff_refs: [],
    },
  },
  gap_review: {
    summary: { gap_group_count: 1 },
    groups: [
      {
        group_id: "ontology-gap-review-legacy-term-intent",
        gap_kind: "legacy_term",
        gap_key: "legacy_term:intent",
        review_state: "needs_owner_review",
        recommended_owner_action: "review_legacy_term_for_package_draft",
        recommended_route: "ontology_owner_review",
        proposed_term: "Intent",
        source_spec_count: 1,
        affected_generated_artifact_count: 0,
        source_specs: [{ spec_id: "SG-SPEC-0001", term: "intent" }],
      },
    ],
  },
  compliance: {
    summary: { finding_count: 1 },
    entries: [
      {
        spec_id: "SG-SPEC-0001",
        path: "specs/nodes/SG-SPEC-0001.yaml",
        validation_status: "report_only_findings",
        finding_count: 1,
        terms: ["intent"],
        findings: [
          {
            finding_id: "SG-SPEC-0001.gap.intent",
            severity: "warning",
            classification: "unknown_legacy_term",
            term: "intent",
          },
        ],
      },
    ],
  },
  write_gate: {
    summary: { finding_count: 2 },
    would_reject_in_hard_gate: true,
    write_decision: "review_required",
    findings: [
      {
        finding_id: "active_frame_incomplete",
        severity: "review_required",
        message: "active_frame must resolve ontology/domain/context.",
      },
    ],
  },
  owner_decisions: {
    summary: { review_count: 1 },
    reviews: [
      {
        review_id: "ontology-owner-decision-review-intent",
        decision_id: "ontology-owner-decision-accept-intent",
        decision_state: "accepted",
        review_state: "ready_for_operator_review",
        before_semantic_status: "unknown_legacy_term",
        after_semantic_status: "accepted_term",
        import_recommended: true,
      },
    ],
  },
  legacy_backfill: {
    summary: { small_pr_batch_count: 1 },
    small_pr_batches: [
      {
        batch_id: "legacy-spec-ontology-backfill-batch-001",
        review_state: "ready_for_review",
        recommended_pr_scope: "small_reviewed_terminology_backfill",
        spec_count: 1,
        finding_count: 1,
        writes_ontology_package: false,
        mutates_canonical_specs: false,
        specs: [{ spec_id: "SG-SPEC-0001", unknown_terms: ["intent"] }],
      },
    ],
  },
  artifacts: {
    gap_review_workflow: {
      available: true,
      path: "runs/ontology_gap_review_workflow.json",
      artifact_kind: "ontology_gap_review_workflow",
      schema_version: 1,
      status: "review_required",
    },
  },
  display_limits: { gap_groups: 40 },
  authority_boundary: {
    ontology_workbench_is_authority: false,
    practical_ontology_is_authority: false,
    may_write_ontology_package: false,
    may_update_ontology_lockfile: false,
    may_mutate_canonical_specs: false,
    may_mark_candidate_accepted: false,
    may_import_owner_decision: false,
    may_close_semantic_gate: false,
  },
};
